// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0; // XOR base
        
        for (char c : s.toCharArray()) {
            result ^= c;  // XOR all chars in s
        }
        for (char c : t.toCharArray()) {
            result ^= c;  // XOR all chars in t
        }
        
        return result; // The leftover char is the added one
    }
}
